### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by Remi-Gau** [nbeliy/bidsme#1]
FYI 

I will just do a simple first "reorganizing" of the doc, by refactoring into sub-documents to give it a lighter README split the data preparationa and bidsfication steps (it is a lot of scrolling otherwise for the user).

I will try to add some examples of folder structure (`tree`) where it can help most likely by taking them from the example repo. This will prevent the user having to jumpr between repo.

**Comment by nbeliy** [comment]
Cool, thanks a lot!

**Comment by Remi-Gau** [comment]
closing old issues of mine
