### ISSUE TITLE
"feature" suggestion: a small library of plugins

### ISSUE THREAD

**Issue by Remi-Gau** [nbeliy/bidsme#4]
The thought crossed my mind when I realized that bidsme does not do the 3D to 4D conversion "by default".

This seems to be one of the low hanging fruit that should be in a library of plugin because anyone who does functional stuff will have to do this.

Also I think that nibabel can do this so it would not require adding new dependencies.

What do you think?

- [x] 3D to 4D conversion

**Comment by nbeliy** [comment]
Good point. I will look how make such library

**Comment by Remi-Gau** [comment]
Another "obvious" one would a plugin to zip the data: I know that most SPM users won't want it because SPM can't deal with zipped data but I would tend to say that many other apps are cool with zipped data.

Plus I would be tempted to still tell SPM users to zip their raw data if only to nudge them to leave the raw data untouched (SPM has the bad habit of just not helping people adopt good data management practices).

**Comment by nbeliy** [comment]
The zipping data is in plans to be integrated in the main code, with a command line option to switch it on and off. the only difficulty is to how it make general (not only MRI but other modalities also).

**Comment by Remi-Gau** [comment]
Oh cool !!! Well done. But I understand the headache.

**Comment by Remi-Gau** [comment]
When you know "where" you would like to host the library of plugins let me know, and I open a PR for the "3D to 4D concatenation" plugin I am working on.

**Comment by nbeliy** [comment]
For the time delay probably I will make the infrustructure monday. Difficulty is to make the includes optional, do not force the nibabel or pydicom for people who will never use them.

For the concatting 3D to 4D, you need assure 2 things:

- original files must be removed (so bidsme do not double-count them)
- merged file must have its meta-data file, which I'm not sure how it should be merged, or just taking the first one is sufficient. 

Just for help, the `recording` instance (of `Modules.baseModule` main class) have a public field `files` which contains list of all files in current series without path, which can be retrieved using `recPath()` function. If files are removed, from disc, they must be also removed from this list. So using `recording` you do not need to rescan folder.

**Comment by nbeliy** [comment]
I've made a new branch `plugin_tools` which includes the infrastructure of tools for plugin. It is a "draft" version, so feel free to give suggestions.

Overall it works like this:
Folder `plugins/tools` contains individual "library" files with a definitions of static functions. Each file corresponds to a family tools, organised mostly by the external modules they use. For example `General.py` use only standard python library. If collection need some external modules (e.g. nibabel), then they must go into separate file. 
These library files are not loaded automatically (so no __init__.py), just to not force user to install modules they will not use. 
Library must have the standard credit/license header (imposed by university), and must include logger -- so std output will be formatted and logged correctly.

In the plugin file, function can be loaded using standard
```
from plugins.tools.General import CheckSeries
```
and then function called as usual:
```
CheckSeries(out_path, Series[session.session])
```

**Comment by Remi-Gau** [comment]
OK will have a look but not just right now. :smile:

**Comment by nbeliy** [comment]
Included in last release, function 
`plugins.tools.Nibabel.Convert3Dto4D`
