### ISSUE TITLE
invalid default date format in scans.tsv

### ISSUE THREAD

**Issue by Remi-Gau** [nbeliy/bidsme#5]
It seems that the default data format for the scans is not the correct.

Here is the output I get from the BIDS validator.

```
        5: [ERR] Entries in the "acq_time" column of _scans.tsv should be expressed in the following format YYYY-MM-DDTHH:mm:ss (year, month, day, hour (24h), minute, second; this is equivalent to the RFC3339 “date-time” format.  (code: 84 - ACQTIME_FMT)
                ./sub-pilot001/ses-001/sub-pilot001_ses-001_scans.tsv
                        @ line: 2
                        Evidence: 2020-08-27T11:24:05.332500
                ./sub-pilot001/ses-001/sub-pilot001_ses-001_scans.tsv
                        @ line: 3
                        Evidence: 2020-08-27T11:33:05.332500
```

**Comment by nbeliy** [comment]
I was hoping that BIDS allows miliseconds in acq_time...
Easy to fix but I will check if it doesn't broke something else

**Comment by Remi-Gau** [comment]
Actually I was thinking yesterday that having a bids-validator step at the end the CI on gitlab would be a good thing, no?

**Comment by nbeliy** [comment]
The test dataset contain MPM, it will make validator unhappy, I will need to create new test dataset (which be an improvement for sure).

**Comment by Remi-Gau** [comment]
just add a .bidsignore and list the stuff to ignore.

also the bids-validator has options to ignore empty-headers if you are working with dummy nifti files

**Comment by nbeliy** [comment]
Made a branch with fixes that fix this issue and issue #2 
Can you check if it works for you?

**Comment by Remi-Gau** [comment]
That's fixed too. Well done. And thanks. :smile:

**Comment by nbeliy** [comment]
Cool, I will merge then)
Thanks for spotting
